create database contrateME;
USE contrateME;


CREATE TABLE `contrateme`.`cm_usuarios` (
  `CM_USUARIO_COD` INT NOT NULL AUTO_INCREMENT,
  `CM_USUARIO_NOME` VARCHAR(250) NOT NULL,
  `CM_USUARIO_EMAIL` VARCHAR(250) NOT NULL,
  `CM_USUARIO_SENHA` VARCHAR(50) NOT NULL,
  `CM_USUARIO_CODCIDADE` INT NULL,
  `CM_USUARIO_BAIRRO` VARCHAR(250) NOT NULL,
  `CM_USUARIO_ENDERECO` VARCHAR(250) NOT NULL,
  `CM_USUARIO_ENDNO` VARCHAR(50) NULL,
  `CM_USUARIO_CPF` VARCHAR(11) NOT NULL,
  `CM_USUARIO_RG` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CM_USUARIO_COD`));  
  
  
/* Create tables */ 
create table CM_ESTADO (
	CM_ESTADO_CODIGO int primary key,
	CM_ESTADO_SIGLA char(2),
	CM_ESTADO_NOME char(50)
);

create table CM_CIDADE (
	CM_CIDADE_CODIGO int primary key,
	CM_CIDADE_NOME char(100),
	CM_CIDADE_CODESTADO int not null,
	foreign key (CM_CIDADE_CODESTADO) references CM_ESTADO(CM_ESTADO_CODIGO)
);
/* Fim create tables */

ALTER TABLE `contrateme`.`cm_usuarios` 
ADD COLUMN `CM_USUARIO_TIPOCONTA` VARCHAR(1) NULL COMMENT 'P = PESSOA\nE = EMPRESA' AFTER `CM_USUARIO_RG`,
ADD COLUMN `CM_USUARIO_CNPJ` VARCHAR(14) NULL AFTER `CM_USUARIO_TIPOCONTA`;
ALTER TABLE `cm_usuarios`	CHANGE COLUMN `CM_USUARIO_CODCIDADE` `CM_USUARIO_CODCIDADE` INT(11) NOT NULL AFTER `CM_USUARIO_SENHA`;
ALTER TABLE `cm_usuarios`	ADD CONSTRAINT `FK_USUARIO_CODCIDADE` FOREIGN KEY (`CM_USUARIO_CODCIDADE`) REFERENCES `cm_cidade` (`CM_CIDADE_CODIGO`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cm_usuarios`	ADD UNIQUE INDEX `CM_USUARIO_EMAIL` (`CM_USUARIO_EMAIL`);


CREATE TABLE `contrateme`.`cm_pessoal` (
  `CM_PESSOAL_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `CM_PESSOAL_EMAILCONTATO` VARCHAR(250) NULL,
  `CM_PESSOAL_TELCONTATO` VARCHAR(45) NULL,
  `CM_PESSOAL_DTNASCIMENTO` DATE NULL,
  PRIMARY KEY (CM_PESSOAL_CODIGO));

CREATE TABLE CM_NACIONALIDADE (
  CM_NACIO_CODIGO INT NOT NULL AUTO_INCREMENT,
  CM_NACIO_NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY (CM_NACIO_CODIGO)
);

ALTER TABLE `contrateme`.`cm_pessoal` 
ADD COLUMN `CM_PESSOAL_CODUSUARIO` INT NULL AFTER `CM_PESSOAL_DTNASCIMENTO`;

ALTER TABLE `contrateme`.`cm_pessoal` 
ADD CONSTRAINT `FK_PESSOAL_CODUSUARIO`
  FOREIGN KEY (`CM_PESSOAL_CODUSUARIO`)
  REFERENCES `contrateme`.`cm_usuarios` (`CM_USUARIO_COD`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `contrateme`.`cm_pessoal` 
DROP COLUMN `CM_PESSOAL_DTNASCIMENTO`,
ADD COLUMN `CM_PESSOAL_DESCRICAO` BLOB NULL AFTER `CM_PESSOAL_CODUSUARIO`;


CREATE TABLE CM_LINGUAGENS (
  CM_LINGUAGEM_CODIGO INT NOT NULL AUTO_INCREMENT,
  CM_LINGUAGEM_LINGUAGEM VARCHAR(1000) NOT NULL,
  PRIMARY KEY (CM_LINGUAGEM_CODIGO)
);

CREATE TABLE `contrateme`.`cm_pessoallinguagem` (
  `CM_PESSLING_CODIGO` INT NULL,
  `CM_PESSLING_CODPESSOAL` INT NULL,
  `CM_PESSLING_CODLINGUA` INT NULL,
  PRIMARY KEY (`CM_PESSLING_CODIGO`));

ALTER TABLE `contrateme`.`cm_pessoallinguagem` 
CHANGE COLUMN `CM_PESSLING_CODIGO` `CM_PESSLING_CODIGO` INT(11) NOT NULL AUTO_INCREMENT ;


ALTER TABLE cm_pessoallinguagem ADD CONSTRAINT FK_PESSLING_CODPESSOAL FOREIGN KEY (CM_PESSLING_CODPESSOAL)
REFERENCES cm_pessoal (CM_PESSOAL_CODIGO);

ALTER TABLE cm_pessoallinguagem ADD CONSTRAINT FK_PESSLING_CODLINGUA FOREIGN KEY (CM_PESSLING_CODLINGUA)
REFERENCES cm_linguagens (CM_LINGUAGEM_CODIGO);

	ALTER TABLE `contrateme`.`cm_pessoal` 
	ADD COLUMN `CM_PESSOAL_ANEXO` VARCHAR(1500) NULL AFTER `CM_PESSOAL_DESCRICAO`;

ALTER TABLE `contrateme`.`cm_usuarios` 
ADD COLUMN `CM_USUARIO_PRMLOGIN` VARCHAR(45) NULL AFTER `CM_USUARIO_CNPJ`;

ALTER TABLE `cm_pessoal`
	ADD COLUMN `CM_PESSOAL_PHOTO` VARCHAR(1500) NULL DEFAULT NULL AFTER `CM_PESSOAL_ANEXO`;
	
	
CREATE TABLE `CM_EMPRESAVAGA` (
	`CM_EMPVAGA_CODIGO` INT NOT NULL AUTO_INCREMENT,
	`CM_EMPVAGA_EMAILCONTATO` VARCHAR(1500) NULL DEFAULT NULL,
	`CM_EMPVAGA_TELCONTATO` VARCHAR(1500) NULL DEFAULT NULL,
	`CM_EMPVAGA_CODUSUARIO` INT NULL DEFAULT NULL,
	`CM_EMPVAGA_DESCRICAO` BLOB NULL,
	`CM_EMPVAGA_ANEXO` VARCHAR(1500) NULL DEFAULT NULL,
	`CM_EMPVAGA_PHOTO` VARCHAR(1500) NULL DEFAULT NULL,
	PRIMARY KEY (`CM_EMPVAGA_CODIGO`),
	CONSTRAINT `FK_EMPVAGA_CODUSUARIO` FOREIGN KEY (`CM_EMPVAGA_CODUSUARIO`) 
	REFERENCES `cm_usuarios` (`CM_USUARIO_COD`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
;

CREATE TABLE `CM_VAGALINGUAGEM` (
	`CM_VAGALING_CODIGO` INT NOT NULL,
	`CM_VAGALING_CODVAGA` INT NULL,
	`CM_VAGALING_CODLINGUA` INT NULL,
	PRIMARY KEY (`CM_VAGALING_CODIGO`),
	CONSTRAINT `FK_VAGALING_CODVAGA` FOREIGN KEY (`CM_VAGALING_CODVAGA`) REFERENCES `cm_empresavaga` (`CM_EMPVAGA_CODIGO`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_VAGALING_CODLINGUA` FOREIGN KEY (`CM_VAGALING_CODLINGUA`) REFERENCES `cm_linguagens` (`CM_LINGUAGEM_CODIGO`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
;

ALTER TABLE `cm_vagalinguagem` CHANGE COLUMN `CM_VAGALING_CODIGO` `CM_VAGALING_CODIGO` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `cm_pessoal`
	ADD COLUMN `CM_PESSOAL_EMAILTODOS` VARCHAR(1) NULL DEFAULT NULL AFTER `CM_PESSOAL_PHOTO`,
	ADD COLUMN `Coluna 9` VARCHAR(1) NULL DEFAULT NULL AFTER `CM_PESSOAL_EMAILTODOS`;

CREATE TABLE `CM_PESSOALVAGA` (
	`CM_PESSVAGA_CODIGO` INT NOT NULL,
	`CM_PESSVAGA_CODVAGA` INT NOT NULL,
	`CM_PESSVAGA_CODPESSOA` INT NOT NULL,
	PRIMARY KEY (`CM_PESSVAGA_CODIGO`),
	CONSTRAINT `FK_PESSVAGA_CODVAGA` FOREIGN KEY (`CM_PESSVAGA_CODVAGA`) REFERENCES `cm_empresavaga` (`CM_EMPVAGA_CODIGO`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_PESSVAGA_CODPESSOA` FOREIGN KEY (`CM_PESSVAGA_CODPESSOA`) REFERENCES `cm_pessoal` (`CM_PESSOAL_CODIGO`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
;
ALTER TABLE `cm_pessoalvaga`
	CHANGE COLUMN `CM_PESSVAGA_CODIGO` `CM_PESSVAGA_CODIGO` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `contrateme`.`cm_empresavaga` 
ADD COLUMN `CM_EMPVAGA_NOMEVG` VARCHAR(250) NULL AFTER `CM_EMPVAGA_PHOTO`;

	