/*
-- Query: SELECT * FROM contrateme.cm_usuarios
LIMIT 0, 1000

-- Date: 2023-06-15 21:45
*/
INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (2,'José Colaço Filho','jose@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','77545658892','326725271','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (3,'Joana Tatiane Azevedo de Lozano','joana@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','27554036750','326725272','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (4,'Tiago Walter Lovato Marinho de Mello','tiago@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','71352441098','326725273','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (5,'Elisa Burgos de Marin','elisa@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','14155202247','326725274','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (6,'Ezequiel Aragão Delvalle','ezequial@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','13528744316','326725275','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (7,'Aurélio Dante Abreu de Iglesias','aurelio@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','52228857041','326725276','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (8,'Keyla Suzana Barros de Oliveira','keyla@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','14451886198','326725277','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (9,'José Osório Correia Rivera','osorio@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','97271869638','326725278','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (10,'Emanuel Wagner de Brito','emanuel@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','60577475185','326725279','P',NULL,'N');

INSERT INTO contrateme.cm_usuarios (`CM_USUARIO_COD`,`CM_USUARIO_NOME`,`CM_USUARIO_EMAIL`,`CM_USUARIO_SENHA`,`CM_USUARIO_CODCIDADE`,`CM_USUARIO_BAIRRO`,`CM_USUARIO_ENDERECO`,`CM_USUARIO_ENDNO`,`CM_USUARIO_CPF`,`CM_USUARIO_RG`,`CM_USUARIO_TIPOCONTA`,`CM_USUARIO_CNPJ`,`CM_USUARIO_PRMLOGIN`) VALUES (11,'Damião Micael Barros de Duarte','damiao@gmail.com','1',4766,'Sonho Nosso','Rua Fulano de Tal','15','17314616400','326725270','P',NULL,'N');
