/*
-- Query: SELECT * FROM contrateme.cm_pessoal
LIMIT 0, 1000

-- Date: 2023-06-16 19:51
*/
INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (2,'jose@gmail.com','14996521388',2,'Programador experiente em Delphi, MySQL, Git e GitHub, e Ionic. Especializado no desenvolvimento de aplicativos de desktop, web e mobile. Proficiente na linguagem Delphi, com habilidades sólidas em criação de interfaces de usuário intuitivas. Conhecimento avançado em MySQL, incluindo modelagem de banco de dados e otimização de desempenho. Experiente em controle de versão Git e gerenciamento de repositórios no GitHub. Capacidade de criar aplicativos multiplataforma usando o framework Ionic, com habilidades em HTML, CSS e JavaScript. Capacidade comprovada de desenvolver interfaces responsivas e integrar APIs. Forte compreensão de boas práticas de desenvolvimento de software e trabalho colaborativo','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000002\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000002\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (3,'joana@gmail.com','14996521388',3,'Programador experiente em Python, Java, C#, SQL e JavaScript, com conhecimento em frameworks como Django, Spring, .NET e React. Especializado no desenvolvimento de aplicativos web e backend. Habilidades sólidas em Python, com experiência em construção de APIs e automação de tarefas. Proficiente em Java e C#, com conhecimento em desenvolvimento de aplicações corporativas e integração de sistemas. Experiência em bancos de dados SQL, incluindo modelagem, consultas e otimização. Familiaridade com JavaScript e frameworks modernos como React, com capacidade de construir interfaces de usuário dinâmicas e interativas. Conhecimento em metodologias ágeis, como Scrum, e habilidades em trabalho colaborativo e comunicação eficaz.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000003\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000003\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (4,'tiago@gmail.com','14996521388',4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000004\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000004\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (5,'elisa@gmail.com','14996521388',5,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000005\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000005\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (6,'ezequial@gmail.com','14996521388',6,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000006\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000006\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (7,'aurelio@gmail.com','14996521388',7,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000007\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000007\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (8,'keyla@gmail.com','14996521388',8,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000008\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000008\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (9,'osorio@gmail.com','14996521388',9,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000009\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000009\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (10,'emanuel@gmail.com','14996521388',10,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000010\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000010\\Imagem\\photo.jpg');

INSERT INTO contrateme.cm_pessoal (`CM_PESSOAL_CODIGO`,`CM_PESSOAL_EMAILCONTATO`,`CM_PESSOAL_TELCONTATO`,`CM_PESSOAL_CODUSUARIO`,`CM_PESSOAL_DESCRICAO`,`CM_PESSOAL_ANEXO`,`CM_PESSOAL_PHOTO`) VALUES (11,'damiao@gmail.com','14996521388',11,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000011\\\\exemplo-de-curriculo-pronto.jpg','C:\\Users\\etec\\Desktop\\TCC\\Importação Curriculo\\00000000011\\Imagem\\photo.jpg');
