/*
-- Query: SELECT * FROM contrateme.cm_vagalinguagem
LIMIT 0, 1000

-- Date: 2023-06-16 20:37
*/
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (1,1,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (2,1,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (3,1,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (4,1,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (5,1,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (6,1,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (7,1,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (8,2,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (9,2,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (10,2,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (11,2,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (12,2,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (13,2,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (14,2,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (15,3,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (16,3,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (17,3,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (18,3,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (19,3,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (20,3,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (21,3,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (22,4,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (23,4,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (24,4,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (25,4,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (26,4,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (27,4,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (28,4,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (29,5,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (30,5,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (31,5,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (32,5,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (33,5,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (34,5,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (35,5,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (36,6,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (37,6,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (38,6,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (39,6,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (40,6,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (41,6,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (42,6,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (43,7,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (44,7,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (45,7,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (46,7,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (47,7,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (48,7,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (49,7,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (50,8,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (51,8,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (52,8,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (53,8,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (54,8,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (55,8,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (56,8,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (57,9,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (58,9,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (59,9,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (60,9,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (61,9,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (62,9,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (63,9,7);

INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (64,10,1);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (65,10,2);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (66,10,3);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (67,10,4);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (68,10,5);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (69,10,6);
INSERT INTO contrateme.cm_vagalinguagem (`CM_VAGALING_CODIGO`,`CM_VAGALING_CODVAGA`,`CM_VAGALING_CODLINGUA`) VALUES (70,10,7);
